include:
  - docker-compose.shared.yml

services:
  webserver:
    image: nginx:1.27.1
    tty: true
    restart: unless-stopped
    volumes:
      - ./nginx/templates/backend.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/templates/admin-local.conf.template:/etc/nginx/templates/admin.conf.template
      - ../backend:/var/www/backend
      - ../admin:/var/www/admin
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    networks:
      project:
      workstation:
        aliases:
         - ${COMPOSE_PROJECT_NAME}-webserver