version: "3.8"

services:
  php:
    build:
      context: ./php
    volumes:
      - ../backend:/var/www
    environment:
      - TZ=UTC
    depends_on:
      - mysql
    networks:
      - app-net

  node:
    build:
      context: ./node
    volumes:
      - ../frontend:/app/frontend
      - ../backend:/app/backend
    working_dir: /app
    command: sh -c "cd frontend && npm install && npm run dev"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend:/var/www/frontend
      - ../backend:/var/www/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node
    networks:
      - app-net

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql
