include:
  - docker-compose.shared.yml

services:
  webserver:
    image: nginx:1.27.1
    tty: true
    restart: unless-stopped
    volumes:
      - ./nginx/templates/backend.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/templates/frontend-local.conf.template:/etc/nginx/templates/frontend.conf.template
      - ../backend:/var/www/backend
      - ../frontend:/var/www/frontend
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    networks:
      project:
      workstation:
        aliases:
         - ${COMPOSE_PROJECT_NAME}-webserver